### PR TITLE
Update pylexibank

### PR DESCRIPTION
**Pull request by chrzyki**
Update everything as far as I could; a small number of problems with the existing profile:

|   Type | ID                         | Value             | Form              | Graphemes                           | Segments                              |
|-------:|:---------------------------|:------------------|:------------------|:------------------------------------|:--------------------------------------|
|      1 | Eastern_Xiangxi-76_sleep-1 | pa31 #            | pa31 #            | ^ p a 31 + <#> $                    | p a ³¹ + <<#>>                        |
|      1 | Hmong_Daw-78_smoke-1       | ɲɕʰɔ4 #           | ɲɕʰɔ4 #           | ^ ɲɕʰ ɔ 4 + <#> $                   | ɲ tɕʰ ɔ ⁴/ + <<#>>                    |
|      1 | Pa_Na-104_salt-1           | ʓa44 #            | ʓa44 #            | ^ ʓ a 44 + <#> $                    | dʑ a ⁴⁴ + <<#>>                       |
|      1 | Pa_Na-109_worm-1           | gaŋ13=ʑuŋ13 #     | gaŋ13=ʑuŋ13 #     | ^ g a ŋ 13 =ʑ u ŋ 13 + <#> $        | g a ŋ ¹³ → ʑ u ŋ ¹³ + <<#>>           |
|      1 | Pa_Na-11_breast-1          | dai22=bo22 #      | dai22=bo22 #      | ^ d a i 22 = b o 22 + <#> $         | d a i ²² → b o ²² + <<#>>             |
|      1 | Pa_Na-12_burntr-1          | kʰu̯a44 #         | kʰu̯a44 #         | ^ kʰ u̯ a 44 + <#> $                | kʰ w a ⁴⁴ + <<#>>                     |
|      1 | Pa_Na-22_earth-1           | ti53 #            | ti53 #            | ^ t i 53 + <#> $                    | t i ⁵³ + <<#>>                        |
|      1 | Pa_Na-2_ashes-1            | pʰi̯o44 #         | pʰi̯o44 #         | ^ pʰ i̯ o 44 + <#> $                | pʰ j o ⁴⁴ + <<#>>                     |
|      1 | Pa_Na-32_full-1            | pon44 #           | pon44 #           | ^ p o n 44 + <#> $                  | p o n ⁴⁴ + <<#>>                      |
|      1 | Pa_Na-35_green-1           | li̯o31 #          | li̯o31 #          | ^ l i̯ o 31 + <#> $                 | l j o ³¹ + <<#>>                      |
|      1 | Pa_Na-36_hair-1            | pi̯o1-pi̯o1 #     | pi̯o1-pi̯o1 #     | ^ p i̯ o 1 - p i̯ o 1 + <#> $       | p j o ¹/ ← p j o ¹/ + <<#>>           |
|      1 | Pa_Na-39_hear-1            | naŋ44 #           | naŋ44 #           | ^ n a ŋ 44 + <#> $                  | n a ŋ ⁴⁴ + <<#>>                      |
|      1 | Pa_Na-44_knee-1            | fo44=ɕu22 #       | fo44=ɕu22 #       | ^ f o 44 =ɕ u 22 + <#> $            | f o ⁴⁴ → tɕ u ²² + <<#>>              |
|      1 | Pa_Na-52_many-1            | gau35 #           | gau35 #           | ^ g au 35 + <#> $                   | g a u ³⁵ + <<#>>                      |
|      1 | Pa_Na-58_neck-1            | ka13=ƛaŋ13 #      | ka13=ƛaŋ13 #      | ^ k a 13 = ƛ a ŋ 13 + <#> $         | k a ¹³ → tɬ a ŋ ¹³ + <<#>>            |
|      1 | Pa_Na-68_root-1            | ɕʰuŋ313-ɕʰuŋ313 # | ɕʰuŋ313-ɕʰuŋ313 # | ^ ɕʰ u ŋ 31 3 - ɕʰ u ŋ 31 3 + <#> $ | tɕʰ u ŋ ³¹ ³/ ← tɕʰ u ŋ ³¹ ³/ + <<#>> |
|      1 | Pa_Na-69_round-1           | ƛuŋ313 #          | ƛuŋ313 #          | ^ ƛ u ŋ 31 3 + <#> $                | tɬ u ŋ ³¹ ³/ + <<#>>                  |
|      1 | Pa_Na-72_see-1             | pu53 #            | pu53 #            | ^ p u 53 + <#> $                    | p u ⁵³ + <<#>>                        |
|      1 | Pa_Na-7_bite-1             | tau53 #           | tau53 #           | ^ t au 53 + <#> $                   | t a u ⁵³ + <<#>>                      |
|      1 | Pa_Na-83_swim-1            | duŋ53-ʔŋ13 #      | duŋ53-ʔŋ13 #      | ^ d u ŋ 53 - ʔ ŋ 13 + <#> $         | d u ŋ ⁵³ ← ʔ ŋ ¹³ + <<#>>             |
|      1 | Pa_Na-84_tail-1            | la44=ti̯e44 #     | la44=ti̯e44 #     | ^ l a 44 = t i̯ e 44 + <#> $        | l a ⁴⁴ → t j e ⁴⁴ + <<#>>             |

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
I suggest to handle this case using "replacements" in the profile, since you cannot remove them cases otherwise. So you replace ` #` by nothing in the FormSpec.

**Comment by LinguList** [comment]
BTW: we understand the HM phonology better now, so I should maybe give the profile another look later. One can note that in our spreadsheet.

**Comment by chrzyki** [comment]
Thanks, updated. I've also explicitly included on of the separators. Seems like just a number of problems with the profile left:

```
⁵/      s a ⁵/                  sa5
⁴/      s ɛ ⁴/                  sɛ4
¹/      t ǝ u ¹/                tǝu1
³/      h u ³/                  hu3
⁶/      ts ɨ ⁶/                 cɨ6
²/      tʃʰ a u ²/              čʰau2
⁸/      l a ŋ ⁸/                laŋ8
⁷/      t ɔ ⁷/                  tɔ7
ɲ̌      ɲ̌ dʒ e ⁶/              ɲ̌ǯe6
ŋ̮      ŋ̮ ³¹ → m pʰ j o ³¹     ŋ̮31=mpɦi̯o31
<<Ł>>   <<Ł>> j <<ũ>> ²/ ← <<Ł>> j <<ũ>> ²/     Łi̯ũ2-Łi̯ũ2
<<ũ>>   <<Ł>> j <<ũ>> ²/ ← <<Ł>> j <<ũ>> ²/     Łi̯ũ2-Łi̯ũ2
<<ʰ>>   ɲ <<ʰ>> a u ²/          ɲʰau2
```

I've also updated the sheet with respect to checking the HM profile.

**Comment by LinguList** [comment]
Tone values are phonological, so we didn't include them. What one could 
do is just map them to ⁰, we also sometimes just map them to distinctive 
values, but this is not extremely consequent. If you put a note, and 
remap tones to ¹/¹ ²/² ... ⁴/⁴ ... ⁵/⁵ ⁶/⁵¹, etc. (with numbers > 5), 
and in the note, you write that we fake-phonetisize the tones, so the 
numbers are just to distinguish, not to give true pronunciation values, 
which are missing from the source, this should be okay.

**Pull request closed without merging**
